### ISSUE TITLE
Fails to open required file

### ISSUE THREAD

**Issue by tcatlas** [squez/Minecraft-Connect#1]
I get the below error when entering my account information to link.

URL: https://metrocraft.io/forums/usercp.php?action=minecraftconnect&do=link

```
MyBB Internal: One or more warnings occurred. Please contact your administrator for assistance.

Fatal error: require_once(): Failed opening required '/MinecraftConnect/MCAuth.class.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') in /home/USER/public_html/forums/inc/plugins/minecraftconnect.php on line 512
```

**Comment by OLDsquez** [comment]
Support is done through the official release thread (https://community.mybb.com/thread-193428.html), the plugin support forums, or via PM on the MyBB Community Board. Please contact me on there.
